language: go

go:
  - 1.4

env:
 - TEST_ASSETS=false

install:
  - ./hack/verify-jsonformat.sh
  - ./hack/install-etcd.sh
  - ./hack/install-std-race.sh
  - ./hack/install-tools.sh
  - ./hack/build-go.sh

script:
  - PATH=$HOME/gopath/bin:./_output/etcd/bin:$PATH make test WHAT="''" TESTFLAGS="-p=4"

notifications:
  email: false
